### ISSUE TITLE
Error in node v6: TypeError: haystack.get is not a function

### ISSUE THREAD

**Issue by binarykitchen** [coolaj86/node-bufferjs#13] opened 2016-05-02 10:41 UTC
This says all. Happens only on node v6:

```
/home/michael-heuberger/binarykitchen/code/videomail.io/node_modules/bufferjs/indexOf.js:16
        if (haystack.get(i+j) !== needle.get(j)) {
                     ^

TypeError: haystack.get is not a function
    at indexOf (/home/michael-heuberger/binarykitchen/code/videomail.io/node_modules/bufferjs/indexOf.js:16:22)
    at Buffer.exports.indexOf (/home/michael-heuberger/binarykitchen/code/videomail.io/node_modules/bufferstream/lib/fn.js:16:14)
    at BufferStream.split (/home/michael-heuberger/binarykitchen/code/videomail.io/node_modules/bufferstream/lib/buffer-stream.js:30:24)
    at BufferStream.write (/home/michael-heuberger/binarykitchen/code/videomail.io/node_modules/bufferstream/lib/buffer-stream.js:210:17)
    at BufferStream.write (/home/michael-heuberger/binarykitchen/code/videomail.io/node_modules/bufferstream/lib/buffer-stream.js:3:61)
    at IncomingMessage.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at IncomingMessage.emit (events.js:188:7)
    at IncomingMessage.Readable.read (_stream_readable.js:387:10)
    at flow (_stream_readable.js:764:26)

npm ERR! Linux 4.2.0-35-generic
npm ERR! argv "/home/michael-heuberger/.nvm/versions/node/v6.0.0/bin/node" "/home/michael-heuberger/.nvm/versions/node/v6.0.0/bin/npm" "rebuild"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! unicode@0.6.1 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
```

**Comment by nakamin** [comment] 2016-05-06 17:58
Can confirm +1

**Comment by alexbooker** [comment] 2016-05-06 19:54
I only get this error on Windows.

@binarykitchen Are you on Windows?

**Comment by nakamin** [comment] 2016-05-06 19:55
Yeah this has been reproduced by other people too. Only on Windows though.

**Comment by binarykitchen** [comment] 2016-05-07 00:47
me on windoze? no way lol ... yup, linux it is

**Comment by alexbooker** [comment] 2016-05-08 00:42
It's weird that I only experience this on Windows

**Comment by nakamin** [comment] 2016-05-08 01:57
@alexbooker perhaps you need to try from a clean installation?

**Comment by Robert-Frampton** [comment] 2016-05-17 18:19
I'm getting the same error in a travis-ci test, just for Node 6.x.

https://travis-ci.org/liferay/generator-liferay-theme/jobs/126265971

**Comment by pazoozooCH** [comment] 2016-06-01 10:57
+1 Also getting this error on Windows:

```
C:\prog\java\IdeaProjects\me\node_modules\bufferjs\indexOf.js:16
        if (haystack.get(i+j) !== needle.get(j)) {
                     ^

TypeError: haystack.get is not a function
    at indexOf (C:\prog\java\IdeaProjects\me\node_modules\bufferjs\indexOf.js:16:22)
```

My system: 

```
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Martin\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "unicode"
npm ERR! node v6.2.0
npm ERR! npm  v3.5.3
npm ERR! code ELIFECYCLE
```

Any workaround for this?

**Comment by nakamin** [comment] 2016-06-01 12:00
@pazoozooCH, there are two open PR's that can fix this, but it seems like @coolaj86 doesn't maintain this package anymore so it's unlikely that it will be fixed.

**Comment by pazoozooCH** [comment] 2016-06-01 15:16
@nakamin , thanks, we found a solution with another dependency, so it's not that urgent for me anymore :smile:

**Comment by coolaj86** [comment] 2016-06-01 19:37
Sorry, I don't mean to be a bum, just busy with other work these days.

I just have repo access to @alexbooker because he hit me up on twitter, so feel free to ask him for access if you need to fix anything once he pulls in and publishes his patch.

**Comment by nakamin** [comment] 2016-06-01 19:40
@coolaj86 Sorry if came off rude or mean... wasn't the intention :smile:. Giving repo access to @alexbooker is definitley a great idea! I'm sure he'll take care of all the issues.

**Comment by anyong** [comment] 2016-06-03 05:12
Also on linux, FWIW. Actually installed fine on Windows...

**Closed** 2016-06-03 21:36 UTC

**Comment by alexbooker** [comment] 2016-06-03 21:50
@anyong Yeah, I see no reason why this problem would be limited to a platform -- I _suspect_ you aren't running Node 6 on Windows.

--------

I just bumped the version number in 72c7763d07a60d2ac5939013dfa2306c62dd4557 and have updated the [**`bufferjs`** npm module](https://www.npmjs.com/package/bufferjs).

If someone can confirm that the problem is solved, that'd be great, thank you!

**Comment by Robert-Frampton** [comment] 2016-06-04 00:57
I can confirm that I'm no longer getting the error in my travis-ci tests. Thanks @alexbooker

**Comment by alexbooker** [comment] 2016-06-04 11:54
That is terrific! thanks, @Robert-Frampton.
